# Generated by Django 3.2 on 2021-04-09 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='rate',
        ),
        migrations.CreateModel(
            name='Convertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.money')),
            ],
        ),
    ]
