# Generated by Django 3.2 on 2021-04-09 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210409_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertion',
            name='to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='convertion_to', to='user.money'),
            preserve_default=False,
        ),
    ]
